### ISSUE TITLE
Consider deferred compensation?

### ISSUE THREAD

**Issue by kelle** [astropy/project#29]
For those that cant earn as part of their current contracts, maybe they accumulate hours, and we pay them at a later date? Can we do that?

**Comment by hamogu** [comment]
At least in the US, the answer is "No". If you are not allowed to work on the side, then you can't work on the side. When you get played is not relevant for if you are allowed to do the work in the first place. (I've gone through this with a lawyer in a an analogous situation, where the limit was not from a contract, but from a visa..)

**Comment by jdswinbank** [comment]
I'm sure that's definitely the case for some types of visa, and we absolutely wouldn't want to run any risks with people's legal status.

I wonder about what sort of contract this is, though — an employer presumably doesn't normally have the right to prevent you from working for somebody else at the same time, as long as you're otherwise legally entitled to do so. It'd be interesting to find out more about what the problem we're actually trying to solve here is.

**Comment by hamogu** [comment]
As I understand it, the problem this questions discusses is this: Some contracts prohibit employees from working for a second employer (or as a free-lancer for an institution) in a same field on the side - a non-competition clause. Say, you are an analyst for Bank of America, then you can't work an an analyst for Chase on the side. 

It's one thing if clauses like this make sense, but they do exist and I don't think that "do the work now and we pretend that you really did it in 2022 after you stopped working for X" is a way to solve it.
