### ISSUE TITLE
Lynn (Numfocus) will look into overhead rate for subawards

### ISSUE THREAD

**Issue by kelle** [astropy/project#36]
Can we pay full overhead on subawards (e.g., to UW or Hunter) from the Moore funding or are we limited to the 10-15% required by Moore.

**Comment by hamogu** [comment]
@astrofrog is correct. Details are here:  https://www.moore.org/docs/default-source/Grantee-Resources/indirect-cost-policy.pdf
We are limited on 12.5% all the way through. That means that any subaward can only charge 12.5% overhead and that NumFOCUS as our fiscal sponsor cannot charge any overhead (even if UW or Hunter charge less than 12.5%) on the fraction of the Moore grants that is passed though to subawards or contractors.

**Comment by jdswinbank** [comment]
Since UW came up here, even though the issue is closed it may be worth mentioning that this wouldn't be a problem: UW would honour the sponsor F&A rate in this case (see [the relevant policy](https://www.washington.edu/research/policies/gim-13-facilities-and-administrative-fa-rates/#policy). I don't know that the same would apply everywhere, but I'd expect this provision is common.
